# Generated by Django 4.2 on 2023-05-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='is_verifed',
            new_name='is_verified',
        ),
    ]
