# Generated by Django 4.2 on 2023-05-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0002_rename_is_verifed_users_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
