# Generated by Django 4.2 on 2023-05-13 11:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0003_users_deleted_at_users_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='device_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, null=True, size=None),
        ),
    ]
