# Generated by Django 4.2 on 2023-05-13 11:55

import django.contrib.postgres.fields
from django.db import migrations, models
import products.validations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0004_users_device_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='device_ids',
        ),
        migrations.AddField(
            model_name='users',
            name='devices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(validators=[products.validations.validate_device_id]), blank=True, null=True, size=None),
        ),
    ]
