# Generated by Django 4.2 on 2023-05-14 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0005_remove_users_device_ids_users_devices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='devices',
        ),
    ]
