# Generated by Django 4.2 on 2023-05-01 12:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('alert', 'alert'), ('drop', 'drop'), ('block', 'block'), ('log', 'log'), ('pass', 'pass')], default='alert')),
                ('name', models.CharField(max_length=100)),
                ('code', models.TextField()),
            ],
        ),
    ]
