# Generated by Django 4.2 on 2023-05-17 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0005_rule_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='is_verifed',
            new_name='is_verified',
        ),
    ]
