# Generated by Django 4.2 on 2023-05-10 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_device_brand_alter_device_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='brand',
            new_name='brand_id',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='category',
            new_name='category_id',
        ),
    ]
