# Generated by Django 4.2 on 2023-05-10 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_brand_device_brand_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='brand_id',
        ),
        migrations.RemoveField(
            model_name='device',
            name='category_id',
        ),
        migrations.AddField(
            model_name='device',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.brand'),
        ),
        migrations.AddField(
            model_name='device',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
    ]
