# Generated by Django 4.2 on 2023-05-10 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_device_brand_id_remove_device_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='products.brand'),
        ),
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='products.category'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('category', 'brand')},
        ),
    ]
