# Generated by Django 4.2 on 2023-05-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_deviceserial_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceserial',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deviceserial',
            name='organization_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
